### ISSUE TITLE
Issue with Forwarding Logs Using opentelemetry.yaml Configuration

### ISSUE THREAD

**Issue by GeertHuygen** [shopware/opentelemetry#16]
**Description:**  
Hi,  

I am experiencing an issue when trying to set up log forwarding as described in the documentation for the `shopware/opentelemetry` package.  

Here's what I did:  

1. I installed the package using Composer:
   ```bash
   composer require shopware/opentelemetry
   ```

2. I added the provided configuration to my `config/packages/opentelemetry.yaml` file:  

   ```yaml
   monolog:
       handlers:
           main:
               type: service
               id: monolog.handler.open_telemetry
           elasticsearch:
               type: service
               id: monolog.handler.open_telemetry
   ```

3. When I attempt to use this configuration, I encounter the following error:  

   ```
   You have requested a non-existent service "monolog.handler.open_telemetry".
   ```

---

**What I Tried:**  
I searched online for a `monolog.handler.open_telemetry` service and found the package [`open-telemetry/opentelemetry-logger-monolog`](https://packagist.org/packages/open-telemetry/opentelemetry-logger-monolog). After installing it with Composer, the error went away, but I am unable to get it working as intended.  

---

**Questions:**  
1. Is there some additional step required to enable or configure the `monolog.handler.open_telemetry` service?  
2. Is the documentation up-to-date for this package?  
3. Should the `open-telemetry/opentelemetry-logger-monolog` package be used alongside `shopware/opentelemetry`?  

Thank you in advance for your help!
